version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/tusenfryd
      - SESSION_SECRET=your_secret_key
    depends_on:
      - db

  db:
    image: mongo:5
    container_name: tusenfryd_db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data: